# Generated by Django 4.1.5 on 2023-01-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="app_service", to="myuser.service"
            ),
        ),
    ]
