# Generated by Django 4.1.5 on 2023-01-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myuser", "0002_alter_appointment_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ManyToManyField(
                blank=True, related_name="app_service", to="myuser.service"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_attendance",
                to="myuser.staff",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="myuser.product",
            ),
        ),
    ]
