"""Migration for attendance."""

# Generated by Django 4.1.7 on 2023-03-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for attendance."""

    dependencies = [
        ("myuser", "0003_alter_appointment_service_alter_attendance_staff_and_more"),  # noqa: E501
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="in_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="in_time",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="out_date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="out_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_present",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
